import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import classes from "./layout.module.css";
import Navigation from "@/components/navigation/Navigation";

const openSans = Open_Sans({
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className={classes.container}>
          <div className={classes.leftSection}>
            <Navigation />
          </div>
          <div className={classes.rightSection}>{children}</div>
        </div>
      </body>
    </html>
  );
}
