import { Priority, Stage, Task } from "@/types/Task";

export const tasks: Task[] = [
  {
    id: "1",
    title: "Setup project repository",
    priority: Priority.HIGH,
    checkList: [
      { id: "1-1", status: true, task: "Create Git repository" },
      { id: "1-2", status: false, task: "Add initial commit" },
    ],
    date: "2024-11-01",
    stage: Stage.BACKLOG,
    assignee: "Alice",
  },
  {
    id: "2",
    title: "Implement authentication",
    priority: Priority.HIGH,
    checkList: [
      { id: "2-1", status: false, task: "Design login UI" },
      { id: "2-2", status: false, task: "Implement JWT tokens" },
    ],
    date: "2024-11-02",
    stage: Stage.TO_DO,
    assignee: "Bob",
  },
  {
    id: "3",
    title: "Database schema design",
    priority: Priority.MEDIUM,
    checkList: [
      { id: "3-1", status: true, task: "Define entities" },
      { id: "3-2", status: false, task: "Setup foreign keys" },
    ],
    date: "2024-11-03",
    stage: Stage.IN_PROGRESS,
    assignee: "Charlie",
  },
  {
    id: "4",
    title: "Create API documentation",
    priority: Priority.LOW,
    checkList: [
      { id: "4-1", status: false, task: "Write endpoint details" },
      { id: "4-2", status: false, task: "Document request/response structure" },
    ],
    date: "2024-11-04",
    stage: Stage.BACKLOG,
    assignee: "David",
  },
  {
    id: "5",
    title: "Frontend component styling",
    priority: Priority.MEDIUM,
    checkList: [
      { id: "5-1", status: true, task: "Style header component" },
      { id: "5-2", status: false, task: "Style footer component" },
    ],
    date: "2024-11-05",
    stage: Stage.TO_DO,
    assignee: "Eve",
  },
  {
    id: "6",
    title: "Testing setup",
    priority: Priority.HIGH,
    checkList: [
      { id: "6-1", status: false, task: "Configure Jest" },
      { id: "6-2", status: false, task: "Write initial test cases" },
    ],
    date: "2024-11-06",
    stage: Stage.IN_PROGRESS,
    assignee: "Alice",
  },
  {
    id: "7",
    title: "Implement CI/CD pipeline",
    priority: Priority.HIGH,
    checkList: [
      { id: "7-1", status: false, task: "Setup GitHub Actions" },
      { id: "7-2", status: false, task: "Define build and deploy stages" },
    ],
    date: "2024-11-07",
    stage: Stage.BACKLOG,
    assignee: "Bob",
  },
  {
    id: "8",
    title: "User profile page",
    priority: Priority.MEDIUM,
    checkList: [
      { id: "8-1", status: false, task: "Create profile UI" },
      { id: "8-2", status: false, task: "Link to user data" },
    ],
    date: "2024-11-08",
    stage: Stage.TO_DO,
    assignee: "Charlie",
  },
  {
    id: "9",
    title: "Implement authorization",
    priority: Priority.HIGH,
    checkList: [
      { id: "9-1", status: false, task: "Define roles and permissions" },
      { id: "9-2", status: false, task: "Secure API endpoints" },
    ],
    date: "2024-11-09",
    stage: Stage.IN_PROGRESS,
    assignee: "David",
  },
  {
    id: "10",
    title: "Set up error handling",
    priority: Priority.MEDIUM,
    checkList: [
      { id: "10-1", status: true, task: "Add error middleware" },
      { id: "10-2", status: false, task: "Implement logging" },
    ],
    date: "2024-11-10",
    stage: Stage.DONE,
    assignee: "Eve",
  },
  {
    id: "11",
    title: "Create landing page",
    priority: Priority.LOW,
    checkList: [
      { id: "11-1", status: true, task: "Design mockups" },
      { id: "11-2", status: false, task: "Implement responsive layout" },
    ],
    date: "2024-11-11",
    stage: Stage.BACKLOG,
    assignee: "Alice",
  },
  {
    id: "12",
    title: "Configure caching",
    priority: Priority.MEDIUM,
    checkList: [
      { id: "12-1", status: false, task: "Implement Redis caching" },
      { id: "12-2", status: false, task: "Cache frequently used data" },
    ],
    date: "2024-11-12",
    stage: Stage.TO_DO,
    assignee: "Bob",
  },
  {
    id: "13",
    title: "Implement search functionality",
    priority: Priority.HIGH,
    checkList: [
      { id: "13-1", status: false, task: "Setup search index" },
      { id: "13-2", status: false, task: "Optimize query performance" },
    ],
    date: "2024-11-13",
    stage: Stage.IN_PROGRESS,
    assignee: "Charlie",
  },
  {
    id: "14",
    title: "Setup notification system",
    priority: Priority.MEDIUM,
    checkList: [
      { id: "14-1", status: true, task: "Define notification structure" },
      { id: "14-2", status: false, task: "Integrate with frontend" },
    ],
    date: "2024-11-14",
    stage: Stage.DONE,
    assignee: "David",
  },
  {
    id: "15",
    title: "Data migration",
    priority: Priority.HIGH,
    checkList: [
      { id: "15-1", status: false, task: "Backup old data" },
      { id: "15-2", status: false, task: "Migrate to new schema" },
    ],
    date: "2024-11-15",
    stage: Stage.BACKLOG,
    assignee: "Eve",
  },
  {
    id: "16",
    title: "Build analytics dashboard",
    priority: Priority.LOW,
    checkList: [
      { id: "16-1", status: false, task: "Create data visualizations" },
      { id: "16-2", status: false, task: "Link to analytics API" },
    ],
    date: "2024-11-16",
    stage: Stage.TO_DO,
    assignee: "Alice",
  },
  {
    id: "17",
    title: "Add dark mode feature",
    priority: Priority.MEDIUM,
    checkList: [
      { id: "17-1", status: false, task: "Design color palette" },
      { id: "17-2", status: false, task: "Implement theme switcher" },
    ],
    date: "2024-11-17",
    stage: Stage.IN_PROGRESS,
    assignee: "Bob",
  },
  {
    id: "18",
    title: "Optimize images for SEO",
    priority: Priority.LOW,
    checkList: [
      { id: "18-1", status: true, task: "Compress images" },
      { id: "18-2", status: false, task: "Add alt tags" },
    ],
    date: "2024-11-18",
    stage: Stage.DONE,
    assignee: "Charlie",
  },
  {
    id: "19",
    title: "Implement live chat support",
    priority: Priority.HIGH,
    checkList: [
      { id: "19-1", status: false, task: "Integrate chat API" },
      { id: "19-2", status: false, task: "Configure chat backend" },
    ],
    date: "2024-11-19",
    stage: Stage.BACKLOG,
    assignee: "David",
  },
  {
    id: "20",
    title: "Write unit tests",
    priority: Priority.HIGH,
    checkList: [
      { id: "20-1", status: false, task: "Test critical functions" },
      { id: "20-2", status: false, task: "Ensure 80%+ coverage" },
    ],
    assignee: "",
    date: "2024-11-20",
    stage: Stage.TO_DO,
  },
];
